{
 "title": "kube-bench",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values({namespace=\"benchmark\"},pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of FAIL by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time( {container=\"kube-bench\",namespace=\"benchmark\"} |= \"[FAIL]\" [$__range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of WARN by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time( {container=\"kube-bench\",namespace=\"benchmark\"} |= \"[WARN]\" [$__range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of FAIL",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time( {container=\"kube-bench\",namespace=\"benchmark\",pod=~\"$pod\"} |= \"[FAIL]\" [$__range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of WARN",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time( {container=\"kube-bench\",namespace=\"benchmark\",pod=~\"$pod\"} |= \"[WARN]\" [$__range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Log in FAIL",
   "type": "logs",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container=\"kube-bench\",namespace=\"benchmark\",pod=~\"$pod\"} |= \"[FAIL]\" | json | line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "Log in WARN",
   "type": "logs",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{container=\"kube-bench\",namespace=\"benchmark\",pod=~\"$pod\"} |= \"[WARN]\" | json | line_format \"{{.log}}\""
    }
   ]
  }
 ]
}