{
 "title": "NFS",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_boot_time_seconds, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_boot_time_seconds{job=~\"$job\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(node_boot_time_seconds{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "NFS Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "rate(node_nfs_connections_total{instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Number of NFS TCP connections"
    }
   ]
  },
  {
   "title": "NFS Packets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "pps", "label": "Packets" }
   ],
   "targets": [
    {
     "expr": "rate(node_nfs_packets_total{protocol=\"tcp\",instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "TCP - NFS network packets (sent+received)"
    },
    {
     "expr": "rate(node_nfs_packets_total{protocol=\"udp\",instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "UDP - NFS network packets (sent+received)"
    }
   ]
  },
  {
   "title": "NFS Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "pps", "label": "Packets" }
   ],
   "targets": [
    {
     "expr": "rate(node_nfs_requests_total{protocol=\"tcp\",instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "TCP - NFS network requests "
    },
    {
     "expr": "rate(node_nfs_requests_total{protocol=\"udp\",instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "UDP - NFS network requests"
    }
   ]
  },
  {
   "title": "NFS RPC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "rate(node_nfs_rpc_authentication_refreshes_total{instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Number of RPC authentication refreshes performed"
    },
    {
     "expr": "rate(node_nfs_rpc_retransmissions_total{instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Number of RPC transmissions performed"
    },
    {
     "expr": "rate(node_nfs_rpcs_total{instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Total number of RPCs performed"
    }
   ]
  }
 ]
}